CREATE TABLE produtos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    detalhes TEXT NOT NULL,
    preco_intervalo VARCHAR(50) NOT NULL,
    doado TINYINT DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE marcas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE produto_marcas (
    produto_id INT,
    marca_id INT,
    PRIMARY KEY (produto_id, marca_id),
    FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE CASCADE,
    FOREIGN KEY (marca_id) REFERENCES marcas(id) ON DELETE CASCADE
);

ALTER TABLE produtos ADD COLUMN link1 VARCHAR(255), ADD COLUMN link2 VARCHAR(255)


INSERT INTO `marcas` (`id`, `nome`, `created_at`, `updated_at`) VALUES (NULL, 'Britania', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (NULL, 'Mondial', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (NULL, 'Electrolux', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (NULL, 'Oster', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP), (NULL, 'Arno', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)

ALTER TABLE produtos ADD COLUMN nome_comprador VARCHAR(255) DEFAULT NULL;
